### ISSUE TITLE
The Ollama running command does not appear.

### ISSUE THREAD

**Issue by anpigon** [your-papa/obsidian-Smart2Brain#117] opened 2024-05-03 10:10 UTC
### What happened?

![image](https://github.com/your-papa/obsidian-Smart2Brain/assets/3969643/284bb517-747f-4455-b5b4-d6b9fe62150a)

### Steps to Reproduce

1. Install the Smart Second Brain plugin for the first time
2. run "Smart Second Brain: Open Chat" from the command palette
3. select "Run on your machine" > "Ollama Daemon"
4. Start Ollama by running this commnad in the terminal and the command does not appear.

### Smart Second Brain Version

1.1.1

### Debug Info

SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.5.12
	Operating system: Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:49 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6020 23.4.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Neo v0.3.2
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 3
	Plugins enabled: 3
		1: BRAT v1.0.1
		2: Hot Reload v0.1.11
		3: Smart Second Brain v1.1.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by Leo310** [comment] 2024-05-03 12:12
duplicate of https://github.com/your-papa/obsidian-Smart2Brain/issues/89

**Closed** 2024-05-03 12:13 UTC
Labels: bug
