### ISSUE TITLE
Request to add Korean! (and other languages)

### ISSUE THREAD

**Issue by BrianJChoi** [your-papa/obsidian-Smart2Brain#99] opened 2024-04-18 12:21 UTC
### Feature Area

Settings

### Describe your idea

Is it possible to add Korean or other languages to the Plugin?

**Comment by nicobrauchtgit** [comment] 2024-04-18 12:49
Duplicate of #11, if you speak Korean it would be great if you could help with the translations :)

**Closed by nicobrauchtgit** 2024-04-18 12:49 UTC
Labels: enhancement

**Comment by BrianJChoi** [comment] 2024-04-18 13:20
I would ljkd to contribute! How can i help with translations?

Sent via Superhuman Android ***@***.***>

**Comment by Leo310** [comment] 2024-04-19 12:51
If you want you can add the i18n language file. The [en.json in src/lang/](https://github.com/your-papa/obsidian-Smart2Brain/blob/0d2c526e2d072f4fa4b957c8ce4765b2f1073cc9/src/lang/en.json) includes all strings that should be translated.

**Comment by BrianJChoi** [comment] 2024-04-19 15:36
Here is a translated version of the en.json file into Korean! (Ko.json)

Sent via Superhuman ***@***.***>

**Comment by Leo310** [comment] 2024-04-21 18:23
@BrianJChoi where exactly is the korean version? If you want you can open a pull request and submit it there
